name: Auto Update Codal RSS

on:
  schedule:
    - cron: '*/30 * * * *' # هر ۳۰ دقیقه یک‌بار خودکار اجرا می‌شود
  workflow_dispatch: # دکمه اجرای دستی در تب Actions

# این دو خط طلایی مشکل خطای ۱۲۸ و عدم دسترسی ربات را برای همیشه حل می‌کند
permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4 # ارتقا به نسخه ۴ برای حل هشدار گیت‌هاب

    - name: Set up Python
      uses: actions/setup-python@v5 # ارتقا به نسخه ۵ برای حل هشدار گیت‌هاب
      with:
        python-version: '3.x'

    - name: Run Script
      run: python codal_rss_generator.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add codal_feed.xml
        git commit -m "Update Codal Feed with all symbols" || exit 0
        git push
