name: Auto Update Codal RSS

on:
  schedule:
    - cron: '*/30 * * * *' # هر ۳۰ دقیقه یک‌بار خودکار اجرا می‌شود
  workflow_dispatch: # دکمه اجرای دستی

permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Script
      run: python codal_rss_generator.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update Codal Feed with all symbols"
        file_pattern: 'codal_feed.xml'
